# Generated by Django 4.0.5 on 2022-06-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
