# Generated by Django 4.0.5 on 2022-06-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rating'),
        ),
    ]
