# Generated by Django 4.0.5 on 2022-06-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rating_alter_room_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rating',
        ),
        migrations.AddField(
            model_name='room',
            name='score',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
